#Billing
#DATA LIST
insert into Billing (BILLING_id, Btypes) values (1, 'past due invoice');
insert into Billing (BILLING_id, Btypes) values (2, 'pro forma invoice');
insert into Billing (BILLING_id, Btypes) values (3, 'interim invoice');
insert into Billing (BILLING_id, Btypes) values (4, 'recurring invoice');
insert into Billing (BILLING_id, Btypes) values (5, 'pro forma invoice');
insert into Billing (BILLING_id, Btypes) values (6, 'final invoice');
insert into Billing (BILLING_id, Btypes) values (7, 'final invoice');
insert into Billing (BILLING_id, Btypes) values (8, 'final invoice');
insert into Billing (BILLING_id, Btypes) values (9, 'pro forma invoice');
insert into Billing (BILLING_id, Btypes) values (10, 'recurring invoice');
insert into Billing (BILLING_id, Btypes) values (11, 'final invoice');
insert into Billing (BILLING_id, Btypes) values (12, 'interim invoice');
insert into Billing (BILLING_id, Btypes) values (13, 'recurring invoice');
insert into Billing (BILLING_id, Btypes) values (14, 'past due invoice');
insert into Billing (BILLING_id, Btypes) values (15, 'pro forma invoice');
insert into Billing (BILLING_id, Btypes) values (16, 'pro forma invoice');
insert into Billing (BILLING_id, Btypes) values (17, 'recurring invoice');
insert into Billing (BILLING_id, Btypes) values (18, 'past due invoice');
insert into Billing (BILLING_id, Btypes) values (19, 'recurring invoice');
insert into Billing (BILLING_id, Btypes) values (20, 'pro forma invoice');
insert into Billing (BILLING_id, Btypes) values (21, 'final invoice');
insert into Billing (BILLING_id, Btypes) values (22, 'final invoice');
insert into Billing (BILLING_id, Btypes) values (23, 'final invoice');
insert into Billing (BILLING_id, Btypes) values (24, 'pro forma invoice');
insert into Billing (BILLING_id, Btypes) values (25, 'recurring invoice');
insert into Billing (BILLING_id, Btypes) values (26, 'recurring invoice');
insert into Billing (BILLING_id, Btypes) values (27, 'recurring invoice');
insert into Billing (BILLING_id, Btypes) values (28, 'interim invoice');
insert into Billing (BILLING_id, Btypes) values (29, 'recurring invoice');
insert into Billing (BILLING_id, Btypes) values (30, 'pro forma invoice');
insert into Billing (BILLING_id, Btypes) values (31, 'pro forma invoice');
insert into Billing (BILLING_id, Btypes) values (32, 'recurring invoice');
insert into Billing (BILLING_id, Btypes) values (33, 'recurring invoice');
insert into Billing (BILLING_id, Btypes) values (34, 'final invoice');
insert into Billing (BILLING_id, Btypes) values (35, 'pro forma invoice');
insert into Billing (BILLING_id, Btypes) values (36, 'final invoice');
insert into Billing (BILLING_id, Btypes) values (37, 'recurring invoice');
insert into Billing (BILLING_id, Btypes) values (38, 'past due invoice');
insert into Billing (BILLING_id, Btypes) values (39, 'pro forma invoice');
insert into Billing (BILLING_id, Btypes) values (40, 'recurring invoice');
