#BlockReason
#DATA LIST
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (1, '2021-01-29', 'sales order blocking reason');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (2, '2021-11-17', 'sales order blocking reason');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (3, '2021-08-14', 'payment not received');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (4, '2021-02-05', 'payment not received');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (5, '2021-01-31', 'sales order blocking reason');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (6, '2021-10-08', 'delivery blocking reason');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (7, '2021-05-20', 'not enough credit');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (8, '2021-08-11', 'billing blocking reason');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (9, '2021-06-25', 'payment not received');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (10, '2021-08-28', 'not enough credit');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (11, '2021-07-04', 'not enough credit');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (12, '2021-10-31', 'billing blocking reason');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (13, '2021-06-05', 'not enough credit');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (14, '2020-11-12', 'sales order blocking reason');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (15, '2021-06-02', 'delivery blocking reason');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (16, '2021-09-13', 'sales order blocking reason');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (17, '2021-10-07', 'billing blocking reason');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (18, '2021-09-25', 'billing blocking reason');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (19, '2021-04-19', 'not enough credit');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (20, '2021-10-08', 'sales order blocking reason');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (21, '2021-07-16', 'not enough credit');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (22, '2021-05-30', 'not enough credit');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (23, '2021-07-08', 'billing blocking reason');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (24, '2021-02-23', 'not enough credit');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (25, '2021-05-24', 'payment not received');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (26, '2021-03-14', 'billing blocking reason');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (27, '2021-06-21', 'delivery blocking reason');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (28, '2020-10-14', 'sales order blocking reason');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (29, '2020-12-16', 'delivery blocking reason');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (30, '2021-09-02', 'delivery blocking reason');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (31, '2021-07-05', 'billing blocking reason');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (32, '2021-01-03', 'payment not received');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (33, '2020-11-09', 'sales order blocking reason');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (34, '2021-01-06', 'payment not received');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (35, '2021-09-26', 'payment not received');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (36, '2020-11-12', 'not enough credit');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (37, '2020-12-14', 'billing blocking reason');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (38, '2021-04-11', 'billing blocking reason');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (39, '2021-03-05', 'payment not received');
insert into BlockReason (Rblocknumber, Rdateissued, Rmotivation) values (40, '2021-07-24', 'payment not received');
