#Deivery
#DATA LIST
insert into Delivery (DELIVERY_id, Dtypes) values (1, 'outbound delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (2, 'outbound delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (3, 'outbound delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (4, 'outbound delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (5, 'replenishment delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (6, 'returns delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (7, 'delivery for stock transfer');
insert into Delivery (DELIVERY_id, Dtypes) values (8, 'returns delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (9, 'inbound delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (10, 'outbound delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (11, 'outbound delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (12, 'delivery for stock transfer');
insert into Delivery (DELIVERY_id, Dtypes) values (13, 'replenishment delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (14, 'inbound delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (15, 'outbound delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (16, 'delivery for stock transfer');
insert into Delivery (DELIVERY_id, Dtypes) values (17, 'inbound delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (18, 'delivery for stock transfer');
insert into Delivery (DELIVERY_id, Dtypes) values (19, 'replenishment delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (20, 'inbound delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (21, 'outbound delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (22, 'inbound delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (23, 'outbound delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (24, 'returns delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (25, 'returns delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (26, 'outbound delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (27, 'returns delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (28, 'returns delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (29, 'outbound delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (30, 'replenishment delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (31, 'delivery for stock transfer');
insert into Delivery (DELIVERY_id, Dtypes) values (32, 'replenishment delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (33, 'replenishment delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (34, 'replenishment delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (35, 'delivery for stock transfer');
insert into Delivery (DELIVERY_id, Dtypes) values (36, 'returns delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (37, 'inbound delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (38, 'replenishment delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (39, 'outbound delivery');
insert into Delivery (DELIVERY_id, Dtypes) values (40, 'delivery for stock transfer');
