#Employee
#DATA LIST
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (1, '8 Springs Place', 'Sally', 'Matthews');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (2, '2 Springview Drive', 'Clarice', 'Marven');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (3, '4 Golden Leaf Lane', 'Ophelia', 'Riccione');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (4, '14933 Leroy Drive', 'Hurlee', 'McCann');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (5, '602 Vahlen Trail', 'Katie', 'Poyser');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (6, '7 Hauk Terrace', 'Vitoria', 'Aleksashin');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (7, '18 Emmet Lane', 'Gradey', 'Gainsborough');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (8, '3476 Sunnyside Park', 'Bradly', 'Le Fleming');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (9, '84710 Debs Park', 'Orbadiah', 'McIlvenna');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (10, '4 Dunning Court', 'Marty', 'Kubis');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (11, '1 Badeau Drive', 'Julie', 'Mervyn');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (12, '2840 Division Road', 'Kaye', 'Murgatroyd');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (13, '594 Shoshone Terrace', 'Dwayne', 'Jahns');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (14, '89 Fulton Place', 'Jay', 'Clubley');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (15, '1242 Scofield Circle', 'Marilin', 'Smither');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (16, '5 Fordem Plaza', 'Camille', 'Wildin');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (17, '84 La Follette Road', 'Field', 'Montel');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (18, '71530 Schiller Place', 'Garrick', 'Aubry');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (19, '54 Waxwing Alley', 'Colas', 'Tiltman');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (20, '4 Anderson Park', 'Carmina', 'Vasiliev');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (21, '6311 Wayridge Parkway', 'Jennilee', 'Komorowski');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (22, '841 Florence Junction', 'Amerigo', 'Spargo');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (23, '13625 Pond Center', 'Berte', 'Cousen');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (24, '626 Truax Road', 'Benedick', 'Artz');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (25, '5787 North Alley', 'Mendy', 'Hills');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (26, '97102 Grim Circle', 'Julita', 'Pluvier');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (27, '59284 Logan Road', 'Marylou', 'Shooter');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (28, '862 Tomscot Alley', 'Cosme', 'McIntosh');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (29, '1705 Helena Plaza', 'Baird', 'Melendez');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (30, '31664 7th Drive', 'Catie', 'Tawse');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (31, '9352 Sugar Drive', 'Rosabel', 'Beldon');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (32, '732 Monument Center', 'Codi', 'Strase');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (33, '5088 Ruskin Trail', 'Moria', 'Nickolls');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (34, '38 Loftsgordon Way', 'Hunt', 'Collerd');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (35, '139 Vera Park', 'Tabby', 'Crippin');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (36, '1886 Becker Avenue', 'Sandi', 'Jenkins');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (37, '29 Lien Drive', 'Kelsy', 'Owtram');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (38, '0807 Sunnyside Crossing', 'Marcellina', 'Mignot');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (39, '3308 Russell Trail', 'Vilhelmina', 'Baildon');
insert into EmployeeGManager (Essn, Eaddress, Ename, Esurname) values (40, '947 Dexter Road', 'Elsinore', 'Veld');
